### ISSUE TITLE
大大查询ip地区接口能否更改为本地查询

### ISSUE THREAD

**Issue by taotaoli123** [tongsq/proxy-collect#1]
我这边使用的短效代理,需要非常快的标记地区,ip138接口查询完毕,有的代理就失效了....
希望大大能引入纯真库查询 支持多个ip查询
项目地址:https://github.com/freshcn/qqwry

**Comment by tongsq** [comment]
可以的，我这两天加一下相关功能 @taotaoli123

**Comment by tongsq** [comment]
已添加本地ip库的支持，同时改为ip检测有效后即时更新ip信息[https://github.com/tongsq/proxy-collect/commit/9767a50a40ac850f8842e0522e71807831a452e4](url)

**Comment by taotaoli123** [comment]
谢谢大大
