### ISSUE TITLE
大佬有兴趣接一个推广吗

### ISSUE THREAD

**Issue by sssssshift** [tongsq/proxy-collect#10]

**Comment by tongsq** [comment]
什么意思

**Comment by sssssshift** [comment]
给我们的产品在您的文章里挂一个图文广告 我们这边给到相应辛苦费



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
23/04/11
09:39:24

tongsq ***@***.***> 于2023年4月10日周一 15:30写道：

**Comment by tongsq** [comment]
你们的产品是什么样的 有多少辛苦费呢

**Comment by sssssshift** [comment]
全球IP代理 费用不会太多（这里不好说金额） 主要是返利模式 因为图文都是我们提供的 操作简单快捷 您只要复制粘贴即可



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
23/04/11
11:10:12

tongsq ***@***.***> 于2023年4月11日周二 09:43写道：

**Comment by choold** [comment]
为什么我邮箱会收到会自动答复的邮件？？？

从 Windows 版邮件发送

发件人: sssssshift
发送时间: 2023年4月11日 11:12
收件人: tongsq/proxy-collect
抄送: Subscribed
主题: Re: [tongsq/proxy-collect] 大佬有兴趣接一个推广吗 (Issue #10)

全球IP代理 费用不会太多（这里不好说金额） 主要是返利模式 因为图文都是我们提供的 操作简单快捷 您只要复制粘贴即可 



[image: Mailtrack] 
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&> 
Sender 
notified by 
Mailtrack 
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&> 
23/04/11 
11:10:12 

tongsq ***@***.***> 于2023年4月11日周二 09:43写道：

**Comment by sssssshift** [comment]
啊哈？沃野不知道



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
23/04/11
11:25:49

choold ***@***.***> 于2023年4月11日周二 11:22写道：

**Comment by sssssshift** [comment]
哦好像是因为我通过邮件发你了哈哈哈

**Comment by choold** [comment]
6














在 2023-04-11 11:27:20，"sssssshift" ***@***.***> 写道：

哦好像是因为我通过邮件发你了哈哈哈
