### ISSUE TITLE
更新后的bug

### ISSUE THREAD

**Issue by taotaoli123** [tongsq/proxy-collect#2]
大大更新后运行几个小时报错，错误从dos窗口直接复制的，可能会不通顺！
看到job.go中“c.AddJob("@every 5m", scheduler.UpdateIpInfo{})”还在使用ip138查询，直接给注释了，不知道不是因为这个引起的报错，只会一点简单的php，基本靠猜。
如果方便的话请留个联系方式，方便沟通。联系方式可以写在“conf.yaml”的注释中，很隐蔽的-_-

“panic: runtime error: index out of range [0] with length 0”

goroutine 1409 [running]:
proxy-collect/service/ip.(*localIpService).readMode(...)
        c:/go/code/proxy-collect-master/service/ip/local_ip_service.go:113
proxy-collect/service/ip.(*localIpService).Find(0xc00001e010, {0xc00db11620, 0xd})
        c:/go/code/proxy-collect-master/service/ip/local_ip_service.go:75 +0x492
proxy-collect/service/ip.GetIpInfo({0xc00db11620, 0xd}, {0xc00db11618, 0x5})
        c:/go/code/proxy-collect-master/service/ip/service.go:20 +0x45
proxy-collect/service.(*proxyService).CheckProxyAndSave(0x406e40?, {0xc00db11620, 0xd}, {0xc00db11618, 0x5}, {0x0, 0x0})
        c:/go/code/proxy-collect-master/service/proxy_service.go:120 +0x62bproxy-collect/scheduler.CheckActiveIp.Run.func1()
        c:/go/code/proxy-collect-master/scheduler/check_active_ip.go:25 +0x3a
github.com/tongsq/go-lib/component.(*Pool).workerStart(0xc000094c18, 0xc0016fcb40?, 0x0?)
        C:/Users/taotao/go/pkg/mod/github.com/tongsq/go-lib@v1.1.4/component/task_pool.go:19 +0x62
created by github.com/tongsq/go-lib/component.(*Pool).RunTask
        C:/Users/taotao/go/pkg/mod/github.com/tongsq/go-lib@v1.1.4/component/task_pool.go:31 +0x11e
exit status 2

**Comment by tongsq** [comment]
你好，这个报错是读取纯真ip库时发生的异常，已经加了异常的捕获，你拉一下最新代码就好了。联系方式可加我QQ:2653077370
